config/routes.rb
Tocantinsemfoco::Application.routes.draw do
  resources :posts

  resources :ads

  resources :pages

  resources :configurations

  resources :users
  match 'player', :controller => 'main', :action => 'player'
  get "main/home"
  match 'anuncio/:id', :controller => 'ads', :action => 'go'
  match "noticia/:id", :controller => 'main', :action => 'noticia'
  match "pagina/:id", :controller => 'main', :action => 'pagina'

  
  get "main/login"
  get "main/logout"
  post "main/do_login"

  get "main/config"
  match "bemvindo", :controller => 'configurations', :action => 'home'

  root :to => "main#home"

end

app/models/configuration.rb
class Configuration < ActiveRecord::Base
end

app/controllers/configurations_controller.rb
class ConfigurationsController < ApplicationController

  def home
    @configuration_stream = Configuration.find_by_tipo_and_label("radio","stream")
    @notice = params[:notice]
  end
  # GET /configurations
  # GET /configurations.xml
  def index
    @configurations = Configuration.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @configurations }
    end
  end

  # GET /configurations/1
  # GET /configurations/1.xml
  def show
    @configuration = Configuration.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @configuration }
    end
  end

  # GET /configurations/new
  # GET /configurations/new.xml
  def new
    @configuration = Configuration.new


    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @configuration }
    end
  end

  # GET /configurations/1/edit
  def edit
    @configuration = Configuration.find(params[:id])
  end

  # POST /configurations
  # POST /configurations.xml
  def create
    @configuration = Configuration.new(params[:configuration])

    respond_to do |format|
      if @configuration.save
        format.html { redirect_to(@configuration, :notice => 'Configuração Salva!') }
        format.xml  { render :xml => @configuration, :status => :created, :location => @configuration }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @configuration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /configurations/1
  # PUT /configurations/1.xml
  def update
    @configuration = Configuration.find(params[:id])

    respond_to do |format|
      if @configuration.update_attributes(params[:configuration])
        format.html { redirect_to({:action=>"home"}, :notice => 'Configuração Atualizada!') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @configuration.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /configurations/1
  # DELETE /configurations/1.xml
  def destroy
    @configuration = Configuration.find(params[:id])
    @configuration.destroy

    respond_to do |format|
      format.html { redirect_to(configurations_url) }
      format.xml  { head :ok }
    end
  end
end

app/helpers/configurations_helper.rb
module ConfigurationsHelper
end

app/views/configurations/_form.html.erb
<%= form_for(@configuration) do |f| %>
  <% if @configuration.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@configuration.errors.count, "error") %> prohibited this configuration from being saved:</h2>

      <ul>
      <% @configuration.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>
  <div class="field">
    <%= f.label :label %>
    <%= f.text_field :label %>
  </div>
  <div class="field">
    <%= f.label :value %>
    <%= f.text_field :value %>
  </div>
  
  <div class="actions">
    <%= f.submit "Criar" %>
  </div>
<% end %>

app/views/configurations/edit.html.erb
<%= link_to 'Detalhes', @configuration,:class=>"link_bt" %> |
<%= link_to 'Voltar', configurations_path,:class=>"link_bt" %>

<h1>Editar Parâmetro de Configuração</h1>

<%= render 'form' %>

app/views/configurations/home.html.erb
<% if @configuration_stream  %>
<fieldset>
  <legend>Configuração da Rádio </legend>
<%= form_for(@configuration_stream) do |f| %>
      <%= f.hidden_field :tipo %>
      <%= f.hidden_field :label %>
    <div class="field">
        <%= f.label :value,"Endereço do Stream" %>
        <%= f.text_field :value %>
    </div>

    <div class="actions">
      <%= submit_tag "Alterar" %>
    </div>
  <% end %>
  </fieldset>
<% end %>

app/views/configurations/index.html.erb
<h1>Painel de Controle</h1>

<table>
  <tr>
    <th>Tipo</th>
    <th>Label</th>
    <th>Value</th>
    <th colspan="3"></th>

  </tr>

<% @configurations.each do |configuration| %>
  <tr>
    <td><%= configuration.tipo %></td>
    <td><%= configuration.label %></td>
    <td><%= configuration.value %></td>
    <td><%= link_to 'Detalhes', configuration,:class=>"link_bt" %></td>
    <td><%= link_to 'Editar', edit_configuration_path(configuration),:class=>"link_bt" %></td>
    <td><%= link_to 'Remover', configuration, :confirm => 'Tem Certeza?', :method => :delete,:class=>"link_bt" %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Novo Parametro de Configuração', new_configuration_path,:class=>"link_bt" %>

app/views/configurations/new.html.erb
<%= link_to 'Voltar', configurations_path,:class=>"link_bt" %>
<h1>Formulário de Criação de Parâmetro de Configuração</h1>

<%= render 'form' %>

app/views/configurations/show.html.erb
<%= link_to 'Editar', edit_configuration_path(@configuration),:class=>"link_bt" %> |
<%= link_to 'Voltar', configurations_path,:class=>"link_bt" %>


<p>
  <b>Tipo:</b>
  <%= @configuration.tipo %>
</p>

<p>
  <b>Label:</b>
  <%= @configuration.label %>
</p>

<p>
  <b>Value:</b>
  <%= @configuration.value %>
</p>