config/routes.rb
Tocantinsemfoco::Application.routes.draw do
  resources :posts

  resources :ads

  resources :pages

  resources :configurations

  resources :users
  match 'player', :controller => 'main', :action => 'player'
  get "main/home"
  match 'anuncio/:id', :controller => 'ads', :action => 'go'
  match "noticia/:id", :controller => 'main', :action => 'noticia'
  match "pagina/:id", :controller => 'main', :action => 'pagina'

  
  get "main/login"
  get "main/logout"
  post "main/do_login"

  get "main/config"
  match "bemvindo", :controller => 'configurations', :action => 'home'

  root :to => "main#home"

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Tocantins em Foco</title>
    <%= stylesheet_link_tag "styles.css" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
  </head>

  <body>
    <!-- HEADER -->
    <div id="header">
      <div id="logo">
        <a onclick="window.open(this.href, this.target, 'width=300,height=230'); return false;" target="popup" href="/player" >
          <img src="/images/radio.jpg" alt="Tocantins em Foco Rádio Online" width="268" height="144" border="0" />
        </a>
      </div>
      <div id="slogan"><img src="/images/slogan.jpg" alt="" width="384" height="58" /></div>
      <!--
      <ul class="buttons">
      <li class="contest"><a href="#" title="Enter Contest">Inicio</a></li>
      <li class="listen"><a href="#" title="Listen Our Station">Sobre</a></li>
      </ul>
      -->
    </div>

    <div id="menu">
      <% if session[:user] %>
          <%= link_to "Página Inicial",root_path %>
          <%= link_to "Anunciantes",ads_path %>
          <%= link_to "Páginas",pages_path %>
          <%= link_to "Notícias",posts_path %>
          <%= link_to "Configurações","/bemvindo" %>
        <div class="right"><%= link_to "Sair",main_logout_path %></div>
      <% end %>
    </div>
    
    <div id="container">
    <% if notice %>
      <p id="notice"> <%= notice %> </p>
    <% end %>

      <%= yield %>
    </div>
    <!-- FOOTER -->
    <!--<div class="sponsor">Sponsored by<a href="http://www.wix.com/free/website?utm_campaign=templateyes&amp;experiment_id=templateyesexp" title="Free Flash Templates" target="_blank"><img src="images/banner-728x90.jpg" alt="Free Flash Templates" width="728" height="90" border="0" /></a></div>-->
  </body>
</html>

app/views/layouts/main.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Tocantins em Foco</title>
    <%= stylesheet_link_tag "styles.css" %>
    <%= javascript_include_tag :defaults %>
    <%= csrf_meta_tag %>
    <link rel="shortcut icon" href="favicon.ico" type="image/x-icon" />
  </head>

  <body>
    <!-- HEADER -->
    <div id="header">
      <ul class="menu">
        <li class="inicio"><a href="/" title="Inicio">Início</a></li>
        <li class="sobre"><a href="<%= "/pagina/#{@sobre.id}"  if @sobre%>" title="Sobre">Sobre</a></li>
        <li class="programa"><a href="<%= "/pagina/#{@programa.id}" if @programa  %>"  title="Programa">Programa</a></li>
        <li class="contato"><a href="<%= "/pagina/#{@contato.id}" if @contato  %>" title="Contato">Contato</a></li>

      </ul>

      <div id="logo">
        <a onclick="window.open(this.href, this.target, 'width=300,height=230'); return false;" target="popup" href="/player" >
          <img src="/images/radio.jpg" alt="Tocantins em Foco Rádio Online" width="268" height="144" border="0" />
        </a>
      </div>
      <div id="slogan"><img src="/images/slogan.jpg" alt="" width="384" height="58" /></div>
      <!--
      <ul class="buttons">
      <li class="contest"><a href="#" title="Enter Contest">Inicio</a></li>
      <li class="listen"><a href="#" title="Listen Our Station">Sobre</a></li>
      </ul>
      -->
    </div>

<div id="content">
      <% if session[:user] %>
        <div class="right"><%= link_to "Sair",main_logout_path %></div>
      <% end %>
      <%= yield %>
</div>
    
    <!-- FOOTER -->
    <div id="footer">
      <p><a href="#">INÍCIO</a> | <a href="#">SOBRE</a> | <a href="#">PROGRAMA</a> |  <a href="#">NOTÍCIAS</a> | <a href="#">CONTATO</a><br/>
        Copyright &copy; <a href="http://www.redrails.com.br">RedRails.com.br</a>. Design por <a href="http://www.twitter.com/LuizCarvalho">Luiz Carvalho</a></p>
    </div>
    <!--<div class="sponsor">Sponsored by<a href="http://www.wix.com/free/website?utm_campaign=templateyes&amp;experiment_id=templateyesexp" title="Free Flash Templates" target="_blank"><img src="images/banner-728x90.jpg" alt="Free Flash Templates" width="728" height="90" border="0" /></a></div>-->
  </body>
</html>